### ISSUE TITLE
卡miui

### ISSUE THREAD

**Issue by ghost** [cokkeijigen/setAppFull#1]
这个插件我在安装后重启卡在了miui界面，我最后无奈只能刷boot后备份后。重新刷机。请大家注意miui13请不要安装

**Comment by cokkeijigen** [comment]
这个我也不知道怎么解决（#捂脸），我更新一下README.md让大家注意一下。

**Comment by ghost** [comment]
我不知道开发者的版本，单就目前而言我miui13安装后重启卡在了miui，我也不敢再试一次了，因为只能刷原版boot后备份后刷机才能解决。
