### ISSUE TITLE
添加开源协议

### ISSUE THREAD

**Issue by Young-Lord** [cokkeijigen/setAppFull#4]
开发者您好，我在[自己的模块](https://github.com/Xposed-Modules-Repo/moe.lyniko.hiderecent)中使用了您的代码作为模板，但由于您的代码没有`LICENSE`不太好办，故能否请您给这个项目增加一分开源协议？
~顺带一提您常量不拉出来定义HelloWorld114514满天飞的行为该改改了~

**Comment by cokkeijigen** [comment]
啊这，现在才发现原来还有人给我提交issue（）
已经添加了GNU GPLv3，反正依托答辩随便用
...不过我看了一眼，你那个不就是100%的kt写的吗，到底用了个啥（我在丢人

**Comment by Young-Lord** [comment]
之前因为性能问题重构了一下，毕竟Jetpack Compose真的很爽x
以及，这是AGPL，不是GPL…
